"""Static semantic table catalog for ask metadata."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class TableMetadata:
    table_name: str
    display_name: str
    domain: str
    description: str
    primary_key: str
    important_columns: tuple[str, ...]
    related_metrics: tuple[str, ...]
    tags: tuple[str, ...]


TABLE_CATALOG: dict[str, TableMetadata] = {
    "order": TableMetadata(
        table_name="order",
        display_name="订单主表",
        domain="交易",
        description="记录用户下单、支付和退款汇总信息。",
        primary_key="id",
        important_columns=(
            "id",
            "order_no",
            "student_id",
            "order_source_channel_id",
            "order_status",
            "paid_amount",
            "refund_amount",
            "paid_at",
            "created_at",
        ),
        related_metrics=("paid_amount", "refund_amount", "conversion_rate"),
        tags=("transaction", "order", "payment"),
    ),
    "order_item": TableMetadata(
        table_name="order_item",
        display_name="订单明细表",
        domain="交易",
        description="记录订单下实际成交的班次商品。",
        primary_key="id",
        important_columns=(
            "id",
            "order_id",
            "student_id",
            "cohort_id",
            "order_item_status",
            "payable_amount",
            "created_at",
        ),
        related_metrics=("paid_amount", "refund_amount", "enrollment_count"),
        tags=("transaction", "order_item", "cohort"),
    ),
    "payment_record": TableMetadata(
        table_name="payment_record",
        display_name="支付记录表",
        domain="交易",
        description="记录支付流水、支付渠道、支付状态和累计退款金额。",
        primary_key="id",
        important_columns=(
            "id",
            "order_id",
            "payment_no",
            "payment_channel",
            "payment_status",
            "amount",
            "refund_amount",
            "paid_at",
            "refund_at",
        ),
        related_metrics=("paid_amount",),
        tags=("transaction", "payment", "income"),
    ),
    "refund_request": TableMetadata(
        table_name="refund_request",
        display_name="退款申请表",
        domain="交易",
        description="记录订单或订单明细级退费申请和审批结果。",
        primary_key="id",
        important_columns=(
            "id",
            "order_id",
            "order_item_id",
            "payment_id",
            "refund_status",
            "apply_amount",
            "approved_amount",
            "refunded_at",
        ),
        related_metrics=("refund_amount",),
        tags=("transaction", "refund"),
    ),
    "student_cohort_rel": TableMetadata(
        table_name="student_cohort_rel",
        display_name="学员班次关系表",
        domain="履约",
        description="记录报名、在读、完成和退费等履约关系。",
        primary_key="id",
        important_columns=(
            "id",
            "student_id",
            "cohort_id",
            "order_item_id",
            "enroll_status",
            "enroll_at",
            "completed_at",
        ),
        related_metrics=("enrollment_count", "completion_rate"),
        tags=("fulfillment", "enrollment", "completion"),
    ),
    "series": TableMetadata(
        table_name="series",
        display_name="课程系列主表",
        domain="课程",
        description="定义课程产品 SPU 和售卖状态。",
        primary_key="id",
        important_columns=(
            "id",
            "delivery_mode",
            "series_code",
            "series_name",
            "sale_status",
            "created_at",
        ),
        related_metrics=("enrollment_count", "refund_amount", "paid_amount"),
        tags=("course", "series", "dimension"),
    ),
    "series_cohort": TableMetadata(
        table_name="series_cohort",
        display_name="班次主表",
        domain="课程",
        description="定义课程系列的招生与交付期次。",
        primary_key="id",
        important_columns=(
            "id",
            "series_id",
            "campus_id",
            "cohort_code",
            "cohort_name",
            "sale_price",
            "current_student_count",
            "yn",
            "start_date",
            "end_date",
        ),
        related_metrics=("enrollment_count", "paid_amount", "refund_amount"),
        tags=("course", "cohort", "dimension"),
    ),
    "org_campus": TableMetadata(
        table_name="org_campus",
        display_name="校区表",
        domain="用户与组织",
        description="定义机构下属校区或办学点信息。",
        primary_key="id",
        important_columns=("id", "campus_code", "campus_name", "city", "yn"),
        related_metrics=("enrollment_count", "paid_amount", "refund_amount"),
        tags=("organization", "campus", "dimension"),
    ),
    "student_profile": TableMetadata(
        table_name="student_profile",
        display_name="学员档案表",
        domain="用户与组织",
        description="定义平台级学员身份、学习目标和画像信息。",
        primary_key="id",
        important_columns=(
            "id",
            "user_id",
            "learner_identity_id",
            "learning_goal_id",
            "education_level_id",
            "grade_id",
            "yn",
        ),
        related_metrics=("enrollment_count", "completion_rate", "attendance_rate"),
        tags=("student", "profile", "dimension"),
    ),
    "dim_learner_identity": TableMetadata(
        table_name="dim_learner_identity",
        display_name="学习者身份维表",
        domain="基础维度",
        description="定义在校生、职场人、求职者等学员身份。",
        primary_key="id",
        important_columns=("id", "identity_code", "identity_name", "yn"),
        related_metrics=("enrollment_count", "completion_rate"),
        tags=("dimension", "learner_identity"),
    ),
    "dim_channel": TableMetadata(
        table_name="dim_channel",
        display_name="招生渠道维表",
        domain="基础维度",
        description="定义机构招生获客渠道。",
        primary_key="id",
        important_columns=(
            "id",
            "channel_category_code",
            "channel_category_name",
            "channel_code",
            "channel_name",
            "yn",
        ),
        related_metrics=("paid_amount", "refund_amount", "conversion_rate"),
        tags=("dimension", "channel", "conversion"),
    ),
    "session_attendance": TableMetadata(
        table_name="session_attendance",
        display_name="课次考勤表",
        domain="学习",
        description="记录学员在课次维度的签到与出勤状态。",
        primary_key="id",
        important_columns=(
            "id",
            "session_id",
            "cohort_id",
            "student_id",
            "attendance_status",
            "checkin_time",
            "created_at",
        ),
        related_metrics=("attendance_rate",),
        tags=("learning", "attendance"),
    ),
    "session_video_play": TableMetadata(
        table_name="session_video_play",
        display_name="视频播放会话表",
        domain="学习",
        description="记录学员观看课次视频的播放会话。",
        primary_key="id",
        important_columns=(
            "id",
            "video_id",
            "student_id",
            "progress_percent",
            "completed_flag",
            "watched_seconds",
            "started_at",
            "ended_at",
        ),
        related_metrics=("completion_rate",),
        tags=("learning", "video"),
    ),
    "session_homework_submission": TableMetadata(
        table_name="session_homework_submission",
        display_name="作业提交表",
        domain="学习",
        description="记录学员作业提交、评分和批改状态。",
        primary_key="id",
        important_columns=(
            "id",
            "homework_id",
            "student_id",
            "session_id",
            "submit_status",
            "total_score",
            "correction_status",
            "submitted_at",
        ),
        related_metrics=("completion_rate",),
        tags=("learning", "homework"),
    ),
    "session_exam_submission": TableMetadata(
        table_name="session_exam_submission",
        display_name="考试作答表",
        domain="学习",
        description="记录学员考试作答、成绩和作答状态。",
        primary_key="id",
        important_columns=(
            "id",
            "exam_id",
            "student_id",
            "attempt_status",
            "duration_seconds",
            "score_value",
            "start_at",
            "submit_at",
        ),
        related_metrics=("completion_rate",),
        tags=("learning", "exam"),
    ),
    "consultation_record": TableMetadata(
        table_name="consultation_record",
        display_name="咨询记录表",
        domain="转化",
        description="记录售前咨询过程，作为转化率指标的咨询侧口径来源。",
        primary_key="id",
        important_columns=("id", "user_id", "cohort_id", "source_channel_id", "consulted_at"),
        related_metrics=("conversion_rate",),
        tags=("conversion", "consultation", "channel"),
    ),
}


def get_table(table_name: str) -> TableMetadata | None:
    return TABLE_CATALOG.get(table_name)


def list_tables() -> tuple[TableMetadata, ...]:
    return tuple(TABLE_CATALOG.values())
